name: CI Webapp - Build & Push Docker

on:
  push:
    branches:
      - main # Assurez-vous que c'est la bonne branche
    paths:
      - 'pitstop-webapp/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Configuration de QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 2. Configuration du Builder (Buildx)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Login à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}
          
      # 4. Définir les variables pour le nom et le tag de l'image
      - name: Set up Image Variables and Metadata
        id: vars
        run: |
          # NE PAS CHANGER : Votre nom d'utilisateur Docker Hub est naimaelmaa
          DOCKER_REPO="naimaelmaa/pitstop-webapp"
          TAG_SHA="${{ github.sha }}"
          
          echo "DOCKER_REPO=$DOCKER_REPO" >> $GITHUB_OUTPUT
          echo "TAGS=$DOCKER_REPO:$TAG_SHA,$DOCKER_REPO:latest" >> $GITHUB_OUTPUT

      # 5. Build de l'image Docker et push vers Docker Hub
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./pitstop-webapp 
          push: true
          tags: ${{ steps.vars.outputs.TAGS }}
          cache-from: type=gha 
          cache-to: type=gha,mode=max

      # 6. vvSCAN DE SÉCURITÉ (DevSecOps)o - Utilisation de Trivy
      - name: Scan Docker Image for Vulnerabilities (Trivy)
        uses: aquasec/trivy-action@0.1.6
        with:
          image-ref: ${{ steps.vars.outputs.DOCKER_REPO }}:${{ github.sha }}
          format: 'table'
          exit-code: '1' # Échoue si des vulnérabilités CRITIQUES ou HAUTES sont détectées
          severity: 'CRITICAL,HIGH'
          output: 'trivy-results.sarif'

      # 7. DÉPLOIEMENT GITOPS - Mise à jour du manifeste Kubernetes
      - name: Update K8s Manifest for GitOps (Deployment)
        uses: azure/k8s-set-context@v3
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          context: default

      - name: Patch K8s Deployment with new Image Tag
        run: |
          K8S_MANIFEST_PATH="k8s/pitstop-webapp/pitstop-webapp-depl.yaml"
          NEW_IMAGE_TAG="${{ steps.vars.outputs.TAGS }}"
          DEPLOYMENT_NAME="pitstop-webapp-depl"
          
          # Mise à jour de l'image dans le manifeste
          sed -i 's|image: .*|image: '$NEW_IMAGE_TAG'|g' $K8S_MANIFEST_PATH

      - name: Commit Updated Manifest
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'GitOps: Update webapp image to ${{ github.sha }}'
          file_pattern: 'k8s/pitstop-webapp/pitstop-webapp-depl.yaml'
